### ISSUE TITLE
有没有直接把pdz转换为pdf的方式？

### ISSUE THREAD

**Issue by crowya** [padeoe/nju-lib-downloader#13]
比如 http://bfts.5read.com/pdz/1263898549252968.pdz 这个链接直接下载的是一个完整的pdz文件。
貌似所有的书籍都能搞到一个完整版pdz的下载地址（我是在iOS上通过截获HTTP的方式找到的）。
而且其中`12638985`就是它的SSID，后面的数字没搞清楚是什么含义，但是随便对比了两本书，发现下载地址的后缀数字是相同的（比如 http://bfts.5read.com/pdz/1217691749252968.pdz ，但是前面数字换成其它书的SSID不一定是有效链接）。
我的想法是，如果通过SSID就能下载书的话会方便不少，甚至不需要校园网，因为从这个网页 http://m.5read.com 就能找到一本书的SSID。
获取完整的下载链接问题不大，但是有了pdz后，如何高效清晰地转换为pdf呢？
网上用xps打印的方法会使清晰度下降，而且页码有时达不到设置的范围，效果不太理想。
所以想问问各位大佬有没有更好的把pdz转换为pdf的方式？

**Comment by padeoe** [comment]
我也不了解pdz，本项目暂不考虑解决该问题
