### ISSUE TITLE
2020/12/28 书香中国已无法使用

### ISSUE THREAD

**Issue by 798886844** [padeoe/nju-lib-downloader#17]
貌似书香中国针对PDF阅读方式做了改进，在网页阅读界面不能直接下载pdf了，变成和超星类似的图片了

![2020122801.png](https://pic.rmb.bdstatic.com/bjh/0f497211348e98fb1764848db2d71a8a.png)

**Comment by padeoe** [comment]
看了下还真是...我抽空更新下
