### ISSUE TITLE
超星下载的不是最高清晰度

### ISSUE THREAD

**Issue by wby238** [padeoe/nju-lib-downloader#3]
以图片的下载地址为例：`http://image1.5read.com/image/ss2jpg.dll?did=bf1&pid=********************&jid=/fow015.jpg&a=*************&zoom=-1&f=0`，这里的`zoom`参数改为**2**（未知是否为最清晰）可获得最高清晰度，稍微对比了一下，程序下载的图片分辨率为`710*897`，而最高的应该是`994*1257`。

**Comment by padeoe** [comment]
感谢！已经在代码中将zoom参数默认改成2了，如果下载失败将继续使用原来的参数。
