### ISSUE TITLE
书香貌似改失效了

### ISSUE THREAD

**Issue by yygcom** [padeoe/nju-lib-downloader#7]
貌似url规则变了，无法下载了，而且单个pdf居然加密了

**Comment by padeoe** [comment]
可能网站在维护，今天看已经恢复了

**Comment by yygcom** [comment]
你看的是哪个网址呢，我这只能看10页了，后面的提示没权限，书香废了

**Comment by padeoe** [comment]
> 你看的是哪个网址呢，我这只能看10页了，后面的提示没权限，书香废了

那是你ip段被网站封禁了吧，我刚刚测试没问题

**Comment by yygcom** [comment]
知道问题是什么了，图书馆的试用期结束了

padeoe <notifications@github.com> 于2019年11月30日周六 下午11:50写道：
